const db = require('./db');

const recipes = [
  { name: 'Chocolate Chip Cookies', description: 'Warm, gooey cookies for a happy mood', mood: 'happy', ingredients: '2 cups flour, 1 cup butter, 1 cup sugar, 2 eggs, 2 cups chocolate chips', instructions: 'Mix dry ingredients. Cream butter and sugar. Add eggs. Combine all and fold in chocolate chips. Bake at 350°F for 10-12 minutes.' },
  { name: 'Rainbow Smoothie Bowl', description: 'A colorful burst of joy in a bowl', mood: 'happy', ingredients: '1 banana, 1 cup berries, 1/2 cup yogurt, 1 tbsp honey, granola, coconut flakes', instructions: 'Blend banana, berries, yogurt and honey until smooth. Pour into bowl. Top with granola and coconut.' },
  { name: 'Ube Halaya Donuts', description: 'Filipino purple yam donuts with a playful twist', mood: 'happy', ingredients: '1 cup ube halaya, 3 cups flour, 2 tsp yeast, 1/2 cup sugar, 1 cup coconut milk, 2 eggs', instructions: 'Mix ube halaya with warm coconut milk and yeast. Add flour, sugar and eggs. Knead, proof 1 hour. Shape into rings, fry until golden. Glaze with ube frosting.' },
  { name: 'Dragon Fruit Poke Bowl', description: 'A vibrant, Instagram-worthy bowl of happiness', mood: 'happy', ingredients: '1 dragon fruit, 2 cups sushi rice, 1 avocado, 1/2 cup edamame, pickled ginger, soy sauce, sesame seeds', instructions: 'Cook and cool sushi rice. Cube dragon fruit and avocado. Arrange rice in bowl, top with fruit, edamame and ginger. Drizzle soy sauce and sprinkle sesame.' },
  { name: 'Mango Sticky Rice', description: 'Thai dessert that tastes like sunshine', mood: 'happy', ingredients: '1 cup glutinous rice, 1 can coconut milk, 2 ripe mangoes, 3 tbsp sugar, toasted sesame seeds', instructions: 'Soak rice 4 hours, steam until tender. Simmer coconut milk with sugar. Pour over rice. Serve with sliced mango and sesame.' },
  { name: 'Grilled Cheese & Tomato Soup', description: 'Classic comfort for when you need warmth', mood: 'sad', ingredients: 'Bread, cheddar cheese, butter, canned tomato soup, milk', instructions: 'Butter bread, add cheese, grill until golden. Heat soup with a splash of milk. Serve together.' },
  { name: 'Creamy Mashed Potatoes', description: 'Soft, comforting and familiar', mood: 'sad', ingredients: '4 potatoes, 1/4 cup butter, 1/2 cup milk, salt, pepper', instructions: 'Boil peeled potatoes until tender. Mash with butter and milk. Season to taste.' },
  { name: 'Oatmeal with Banana', description: 'Gentle and nourishing', mood: 'sad', ingredients: '1 cup oats, 2 cups milk, 1 banana, cinnamon, honey', instructions: 'Cook oats in milk until creamy. Top with sliced banana, cinnamon and honey.' },
  { name: 'Ramen with Soft Egg', description: 'Warm, brothy hug in a bowl', mood: 'sad', ingredients: 'Ramen noodles, chicken or veggie broth, soft-boiled egg, nori, scallions, sesame oil, soy sauce', instructions: 'Boil broth. Cook noodles. Soft-boil egg (6 min). Assemble bowl with noodles, broth, halved egg, nori and scallions. Drizzle sesame oil.' },
  { name: 'Tuna Melt on Rye', description: 'Hearty, nostalgic sandwich comfort', mood: 'sad', ingredients: 'Canned tuna, mayo, celery, cheddar, rye bread, butter', instructions: 'Mix tuna with mayo and diced celery. Pile on rye, top with cheddar. Butter outside, grill until melted and crispy.' },
  { name: 'Rice Pudding with Cardamom', description: 'Creamy, spiced warmth', mood: 'sad', ingredients: '1 cup Arborio rice, 4 cups whole milk, 4 cardamom pods, 1/4 cup raisins, cinnamon', instructions: 'Simmer rice in milk with cardamom until creamy. Add raisins. Serve warm with a sprinkle of cinnamon.' },
  { name: 'Tea & Toast', description: 'Simple, calming comfort', mood: 'stressed', ingredients: 'Tea bag, hot water, bread, butter', instructions: 'Steep tea for 3-5 minutes. Toast bread lightly. Butter and enjoy with tea.' },
  { name: 'Meditation Soup', description: 'Light and soothing miso-based broth', mood: 'stressed', ingredients: '4 cups water, 3 tbsp miso paste, tofu, seaweed, green onions', instructions: 'Heat water. Dissolve miso. Add cubed tofu and seaweed. Top with green onions.' },
  { name: 'Lavender Lemonade', description: 'Calming and refreshing', mood: 'stressed', ingredients: '4 lemons, 4 cups water, 1/4 cup honey, lavender buds', instructions: 'Juice lemons. Steep lavender in hot water. Mix with lemon juice and honey. Chill.' },
  { name: 'Chamomile Oatmeal', description: 'Double-down on calm with tea-infused oats', mood: 'stressed', ingredients: '1 cup steel-cut oats, 2 cups chamomile tea, 1 banana, honey, pinch of salt', instructions: 'Brew strong chamomile tea. Cook oats in tea instead of water. Top with sliced banana and honey.' },
  { name: 'Cucumber Mint Infused Water', description: 'Cool, crisp, zero-fuss hydration', mood: 'stressed', ingredients: '1 cucumber, handful fresh mint, 1 lemon, cold water', instructions: 'Slice cucumber and lemon. Add to pitcher with mint. Fill with cold water. Refrigerate 2 hours. Sip slowly.' },
  { name: 'Soft Scrambled Eggs on Toast', description: 'Gentle, velvety eggs that demand nothing', mood: 'stressed', ingredients: '3 eggs, 1 tbsp butter, chives, sourdough bread, salt', instructions: 'Whisk eggs. Melt butter on low heat. Cook eggs slowly, stirring constantly until barely set. Pile on toasted sourdough. Top with chives.' },
  { name: 'Energy Balls', description: 'Quick protein-packed bites', mood: 'energetic', ingredients: '1 cup oats, 1/2 cup peanut butter, 1/3 cup honey, 1/2 cup chocolate chips', instructions: 'Mix all ingredients. Roll into balls. Refrigerate for 1 hour.' },
  { name: 'Avocado Toast with Egg', description: 'Fuel for an active day', mood: 'energetic', ingredients: '2 slices bread, 1 avocado, 2 eggs, salt, pepper, red pepper flakes', instructions: 'Toast bread. Mash avocado on top. Fry eggs. Place egg on avocado toast. Season.' },
  { name: 'Banana Peanut Butter Smoothie', description: 'Power-packed and delicious', mood: 'energetic', ingredients: '2 bananas, 2 tbsp peanut butter, 1 cup milk, 1 tbsp honey', instructions: 'Blend all ingredients until smooth. Serve immediately.' },
  { name: 'Shakshuka', description: 'Spicy North African eggs in tomato sauce', mood: 'energetic', ingredients: '1 can crushed tomatoes, 2 bell peppers, 4 eggs, cumin, harissa, garlic, onion', instructions: 'Sauté onion and garlic. Add peppers, tomatoes, cumin and harissa. Simmer 10 min. Crack in eggs, cover until set. Serve with bread.' },
  { name: 'Açaí Bowl with Matcha', description: 'Superfood fuel for a busy day', mood: 'energetic', ingredients: 'Açaí pack, 1 banana, granola, coconut flakes, honey, 1 tsp matcha powder', instructions: 'Blend frozen açaí with banana. Pour into bowl. Top with granola, coconut, drizzle of honey and dusting of matcha.' },
  { name: 'Korean Bibimbap', description: 'Rice bowl bursting with color and flavor', mood: 'energetic', ingredients: 'Rice, marinated beef, spinach, carrots, cucumber, gochujang, fried egg', instructions: 'Cook rice. Sauté beef and vegetables separately. Arrange over rice. Top with fried egg and gochujang. Mix and eat.' },
  { name: 'Beef Stew', description: 'Hearty and warming', mood: 'cozy', ingredients: '1 lb beef, potatoes, carrots, onions, beef broth, herbs', instructions: 'Brown beef. Add vegetables and broth. Simmer 2 hours until tender.' },
  { name: 'Mac and Cheese', description: 'Ultimate comfort food', mood: 'cozy', ingredients: 'Pasta, cheddar, butter, milk, flour', instructions: 'Cook pasta. Make cheese sauce with butter, flour, milk and cheese. Mix and bake until bubbly.' },
  { name: 'Hot Cocoa', description: 'Warm and indulgent', mood: 'cozy', ingredients: 'Milk, cocoa powder, sugar, vanilla, marshmallows', instructions: 'Heat milk. Whisk in cocoa and sugar. Add vanilla. Top with marshmallows.' },
  { name: 'Potato Leek Soup', description: 'Silky, buttery, deeply comforting', mood: 'cozy', ingredients: '3 leeks, 4 potatoes, 4 cups broth, 1/2 cup cream, thyme', instructions: 'Sauté sliced leeks. Add cubed potatoes and broth. Simmer 20 min. Blend until smooth. Stir in cream and thyme.' },
  { name: 'Chicken and Dumplings', description: 'Old-fashioned stew with pillowy dumplings', mood: 'cozy', ingredients: 'Chicken thighs, carrots, celery, onion, broth, flour, baking powder, milk', instructions: 'Simmer chicken and vegetables in broth. Mix dumpling batter. Drop spoonfuls into simmering stew. Cover 15 min until fluffy.' },
  { name: 'Baked Apple with Cinnamon', description: 'Warm fruit dessert that smells like home', mood: 'cozy', ingredients: '4 apples, butter, cinnamon, brown sugar, walnuts', instructions: 'Core apples. Stuff with butter, cinnamon and sugar. Bake at 375°F 30 min. Top with walnuts and drizzle of honey.' },
  { name: 'Pasta Carbonara', description: 'Rich and romantic', mood: 'romantic', ingredients: 'Spaghetti, eggs, pancetta, parmesan, black pepper', instructions: 'Cook pasta. Crisp pancetta. Toss hot pasta with eggs, pancetta and parmesan. Serve with pepper.' },
  { name: 'Chocolate Fondant', description: 'Decadent molten dessert', mood: 'romantic', ingredients: 'Butter, chocolate, eggs, sugar, flour', instructions: 'Melt chocolate and butter. Mix with eggs, sugar and flour. Bake until edges set, center molten.' },
  { name: 'Caprese Salad', description: 'Elegant and fresh', mood: 'romantic', ingredients: 'Tomatoes, fresh mozzarella, basil, olive oil, balsamic', instructions: 'Slice tomatoes and mozzarella. Layer with basil. Drizzle oil and balsamic.' },
  { name: 'Seared Scallops with Brown Butter', description: 'Luxurious and impressive', mood: 'romantic', ingredients: 'Sea scallops, butter, lemon, capers, parsley', instructions: 'Pat scallops dry. Sear 2 min per side in hot pan. Remove. Brown butter, add capers and lemon. Pour over scallops.' },
  { name: 'Truffle Risotto', description: 'Decadent and aromatic', mood: 'romantic', ingredients: 'Arborio rice, white wine, parmesan, truffle oil, butter, shallot', instructions: 'Sauté shallot. Toast rice. Deglaze with wine. Add broth ladle by ladle, stirring. Finish with parmesan, butter and truffle oil.' },
  { name: 'Panna Cotta with Berry Coulis', description: 'Silky, elegant dessert', mood: 'romantic', ingredients: 'Cream, gelatin, vanilla, sugar, mixed berries', instructions: 'Bloom gelatin. Heat cream with sugar and vanilla. Add gelatin. Pour into molds, chill 4 hours. Blend berries for coulis. Unmold and serve.' },
  { name: 'Spicy Curry', description: 'Bold and adventurous', mood: 'adventurous', ingredients: 'Chicken, curry paste, coconut milk, vegetables, rice', instructions: 'Sauté curry paste. Add chicken and vegetables. Pour coconut milk. Simmer. Serve with rice.' },
  { name: 'Sushi Rolls', description: 'Try something new', mood: 'adventurous', ingredients: 'Sushi rice, nori, fish or veggies, rice vinegar', instructions: 'Season rice with vinegar. Spread on nori. Add fillings. Roll tightly. Slice.' },
  { name: 'Tacos Al Pastor', description: 'Vibrant and exciting', mood: 'adventurous', ingredients: 'Pork, pineapple, tortillas, cilantro, lime, onions', instructions: 'Marinate pork. Grill with pineapple. Slice and serve in tortillas with toppings.' },
  { name: 'Pho Ga', description: 'Vietnamese chicken noodle soup with star anise and ginger', mood: 'adventurous', ingredients: 'Chicken, rice noodles, star anise, ginger, cinnamon, fish sauce, bean sprouts, basil', instructions: 'Simmer chicken with charred ginger, star anise and cinnamon. Strain broth. Cook noodles. Assemble with shredded chicken, herbs and bean sprouts.' },
  { name: 'Okonomiyaki', description: 'Japanese savory cabbage pancake', mood: 'adventurous', ingredients: 'Cabbage, flour, eggs, pork belly, okonomiyaki sauce, mayo, bonito flakes', instructions: 'Shred cabbage. Mix with flour and eggs. Fry pancake, top with pork. Flip. Serve with okonomiyaki sauce, mayo and bonito.' },
  { name: 'Bun Bo Hue', description: 'Spicy Vietnamese beef noodle soup with lemongrass', mood: 'adventurous', ingredients: 'Beef shank, pork knuckle, rice noodles, lemongrass, shrimp paste, chili oil', instructions: 'Simmer beef and pork with lemongrass. Add shrimp paste and chili. Cook noodles. Serve with herbs, lime and bean sprouts.' },
];

db.exec('DELETE FROM recipes');
const stmt = db.prepare('INSERT INTO recipes (name, description, ingredients, instructions, mood) VALUES (?, ?, ?, ?, ?)');

for (const r of recipes) {
  stmt.run(r.name, r.description, r.ingredients, r.instructions, r.mood);
}

console.log(`Seeded ${recipes.length} recipes.`);
